language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
before_install:
  - gem update bundler
env:
  - TZ=Asia/Tokyo
addons:
  code_climate:
    repo_token: caae755f12d3707ffcce4f5a812daefb4e8aa197730258a82bd7375c31d6cd00
